
exports.salesOrder = {
  '@type': 'org.openmdx.kernel.ResultSet',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder',
    '@hasMore': 'false',
    '@total': '7',
    objects: [
  {
    '@type': 'org.opencrx.kernel.contract1.SalesOrder',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/9DTSXR06DLHPM0EBHQA5MAZ7J',
    '@version': 'bW9kaWZpZWRBdD0yMDIwLTAxLTA3VDExOjA1OjMzLjY3MjAwMFo=',
    priority: 3,
    noAutoRecalc: false,
    isGift: false,
    shippingMethod: 0,
    submitStatus: 0,
    owningUser: [Object],
    salesRep: [Object],
    totalSalesCommission: '0.000000000',
    modifiedBy: [Object],
    contractNumber: 'Telekom_Sallinger_2019',
    calcRule: [Object],
    accessLevelDelete: 2,
    pricingState: 10,
    paymentTerms: 0,
    totalDiscountAmount: '0.000000000',
    freightTerms: 0,
    accessLevelUpdate: 2,
    createdAt: '2020-01-07T10:45:34.872Z',
    createdBy: [Object],
    pricingRule: [Object],
    contractCurrency: 978,
    totalTaxAmount: '467.500000000',
    customer: [Object],
    totalAmount: '5500.000000000',
    identity: 'xri://@openmdx*org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/9DTSXR06DLHPM0EBHQA5MAZ7J',
    totalAmountIncludingTax: '5967.500000000',
    accessLevelBrowse: 3,
    owner: [Object],
    contractLanguage: 0,
    contractState: 1410,
    modifiedAt: '2020-01-07T11:05:33.672Z',
    disabled: false,
    activeOn: '2019-08-01T09:41:01.000Z',
    totalBaseAmount: '5500.000000000',
    name: 'Telekom_Sallinger_2019',
    owningGroup: [Object]
  },
  {
    '@type': 'org.opencrx.kernel.contract1.SalesOrder',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/9DXSKIH1RCHD5H2MA4T2TYJFL',
    '@version': 'bW9kaWZpZWRBdD0yMDE5LTA1LTI2VDEzOjMzOjA3LjE4MjAwMFo=',
    priority: 3,
    noAutoRecalc: false,
    isGift: false,
    shippingMethod: 0,
    submitStatus: 0,
    owningUser: [Object],
    salesRep: [Object],
    totalSalesCommission: '0.000000000',
    modifiedBy: [Object],
    contractNumber: 'German1',
    calcRule: [Object],
    accessLevelDelete: 2,
    pricingState: 10,
    paymentTerms: 0,
    totalDiscountAmount: '0.000000000',
    freightTerms: 0,
    accessLevelUpdate: 2,
    createdAt: '2019-05-26T13:32:08.372Z',
    createdBy: [Object],
    pricingRule: [Object],
    contractCurrency: 978,
    totalTaxAmount: '212.500000000',
    customer: [Object],
    totalAmount: '2500.000000000',
    identity: 'xri://@openmdx*org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/9DXSKIH1RCHD5H2MA4T2TYJFL',
    totalAmountIncludingTax: '2712.500000000',
    accessLevelBrowse: 3,
    owner: [Object],
    contractLanguage: 0,
    contractState: 1410,
    modifiedAt: '2019-05-26T13:33:07.182Z',
    disabled: false,
    activeOn: '2018-02-12T14:32:53.000Z',
    totalBaseAmount: '2500.000000000',
    name: 'German1',
    owningGroup: [Object]
  },
  {
    '@type': 'org.opencrx.kernel.contract1.SalesOrder',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/9DXSKMWV9GXD5H2MA4T2TYJFL',
    '@version': 'bW9kaWZpZWRBdD0yMDE5LTA1LTI2VDEzOjM2OjU2LjYyMDAwMFo=',
    priority: 2,
    noAutoRecalc: false,
    isGift: false,
    shippingMethod: 0,
    submitStatus: 0,
    owningUser: [Object],
    salesRep: [Object],
    totalSalesCommission: '0.000000000',
    modifiedBy: [Object],
    contractNumber: 'Dirk1',
    calcRule: [Object],
    accessLevelDelete: 2,
    pricingState: 10,
    paymentTerms: 0,
    totalDiscountAmount: '0.000000000',
    freightTerms: 0,
    accessLevelUpdate: 2,
    createdAt: '2019-05-26T13:36:28.098Z',
    createdBy: [Object],
    pricingRule: [Object],
    contractCurrency: 978,
    totalTaxAmount: '478.125000000',
    customer: [Object],
    totalAmount: '5625.000000000',
    identity: 'xri://@openmdx*org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/9DXSKMWV9GXD5H2MA4T2TYJFL',
    totalAmountIncludingTax: '6103.125000000',
    accessLevelBrowse: 3,
    owner: [Object],
    contractLanguage: 0,
    contractState: 1410,
    modifiedAt: '2019-05-26T13:36:56.620Z',
    disabled: false,
    activeOn: '2018-02-06T14:35:52.000Z',
    totalBaseAmount: '5625.000000000',
    name: 'Dirk1',
    owningGroup: [Object]
  },
  {
    '@type': 'org.opencrx.kernel.contract1.SalesOrder',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/9ENGNFGDLDQSPH2MA4T2TYJFL',
    '@version': 'bW9kaWZpZWRBdD0yMDE5LTA1LTI2VDEzOjI2OjQ5Ljg0MjAwMFo=',
    priority: 3,
    noAutoRecalc: false,
    isGift: false,
    shippingMethod: 2,
    submitStatus: 0,
    owningUser: [Object],
    salesRep: [Object],
    totalSalesCommission: '0.000000000',
    modifiedBy: [Object],
    contractNumber: 'V1',
    calcRule: [Object],
    accessLevelDelete: 2,
    pricingState: 10,
    paymentTerms: 0,
    totalDiscountAmount: '0.000000000',
    freightTerms: 0,
    accessLevelUpdate: 2,
    createdAt: '2019-05-26T13:08:10.269Z',
    createdBy: [Object],
    pricingRule: [Object],
    contractCurrency: 978,
    totalTaxAmount: '340.000000000',
    customer: [Object],
    totalAmount: '4000.000000000',
    identity: 'xri://@openmdx*org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/9ENGNFGDLDQSPH2MA4T2TYJFL',
    totalAmountIncludingTax: '4340.000000000',
    accessLevelBrowse: 3,
    owner: [Object],
    contractLanguage: 0,
    contractState: 1410,
    modifiedAt: '2019-05-26T13:26:49.842Z',
    disabled: false,
    activeOn: '2018-10-30T14:07:00.000Z',
    totalBaseAmount: '4000.000000000',
    name: 'Telekom2',
    owningGroup: [Object]
  },
  {
    '@type': 'org.opencrx.kernel.contract1.SalesOrder',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/9RAGESCOPWMB0QBF040JB164I',
    '@version': 'bW9kaWZpZWRBdD0yMDIxLTEwLTExVDE3OjAyOjIzLjA0MTAwMFo=',
    priority: 4,
    noAutoRecalc: false,
    isGift: false,
    shippingMethod: 3,
    submitStatus: 0,
    owningUser: [Object],
    salesRep: [Object],
    totalSalesCommission: '0.000000000',
    modifiedBy: [Object],
    contractNumber: 'Dirk2',
    accessLevelDelete: 2,
    pricingState: 0,
    paymentTerms: 0,
    totalDiscountAmount: '0.000000000',
    freightTerms: 0,
    accessLevelUpdate: 2,
    createdAt: '2021-10-11T17:02:23.041Z',
    createdBy: [Object],
    contractCurrency: 978,
    totalTaxAmount: '0.000000000',
    customer: [Object],
    totalAmount: '0.000000000',
    identity: 'xri://@openmdx*org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/9RAGESCOPWMB0QBF040JB164I',
    totalAmountIncludingTax: '0.000000000',
    accessLevelBrowse: 3,
    owner: [Object],
    contractLanguage: 110,
    contractState: 420,
    modifiedAt: '2021-10-11T17:02:23.041Z',
    disabled: false,
    activeOn: '2021-10-13T17:03:41.000Z',
    totalBaseAmount: '0.000000000',
    name: 'Dirk2',
    owningGroup: [Object]
  },
  {
    '@type': 'org.opencrx.kernel.contract1.SalesOrder',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/L4M2BSFAM5GQ3VHF1K43FCO5O',
    '@version': 'bW9kaWZpZWRBdD0yMDIxLTEwLTExVDE2OjQ4OjU1LjI4NzAwMFo=',
    priority: 3,
    noAutoRecalc: false,
    isGift: false,
    shippingMethod: 3,
    submitStatus: 0,
    owningUser: [Object],
    salesRep: [Object],
    totalSalesCommission: '0.000000000',
    modifiedBy: [Object],
    contractNumber: 'Mayer Werft AG-S1613220407',
    calcRule: [Object],
    accessLevelDelete: 2,
    pricingState: 10,
    paymentTerms: 0,
    totalDiscountAmount: '0.000000000',
    freightTerms: 0,
    accessLevelUpdate: 2,
    createdAt: '2021-02-13T12:48:11.746Z',
    createdBy: [Object],
    pricingRule: [Object],
    contractCurrency: 978,
    totalTaxAmount: '0.000000000',
    customer: [Object],
    totalAmount: '0.000000000',
    identity: 'xri://@openmdx*org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/L4M2BSFAM5GQ3VHF1K43FCO5O',
    totalAmountIncludingTax: '0.000000000',
    accessLevelBrowse: 3,
    owner: [Object],
    contractLanguage: 0,
    contractState: 0,
    modifiedAt: '2021-10-11T16:48:55.287Z',
    disabled: false,
    activeOn: '2021-02-14T12:48:33.000Z',
    totalBaseAmount: '0.000000000',
    name: 'Testing',
    owningGroup: [Object]
  },
  {
    '@type': 'org.opencrx.kernel.contract1.SalesOrder',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/L6K69EO6Y3ZS9H2MA4T2TYJFL',
    '@version': 'bW9kaWZpZWRBdD0yMDIxLTEwLTExVDE2OjQ1OjQ4LjIzNTAwMFo=',
    priority: 3,
    noAutoRecalc: false,
    isGift: false,
    shippingMethod: 0,
    submitStatus: 0,
    owningUser: [Object],
    salesRep: [Object],
    totalSalesCommission: '0.000000000',
    modifiedBy: [Object],
    contractNumber: 'Mayer1',
    calcRule: [Object],
    accessLevelDelete: 2,
    pricingState: 10,
    paymentTerms: 0,
    totalDiscountAmount: '0.000000000',
    freightTerms: 0,
    accessLevelUpdate: 2,
    createdAt: '2019-05-26T13:29:08.480Z',
    createdBy: [Object],
    pricingRule: [Object],
    contractCurrency: 978,
    totalTaxAmount: '187.000000000',
    customer: [Object],
    totalAmount: '2200.000000000',
    identity: 'xri://@openmdx*org.opencrx.kernel.contract1/provider/CRX/segment/Standard/salesOrder/L6K69EO6Y3ZS9H2MA4T2TYJFL',
    totalAmountIncludingTax: '2387.000000000',
    accessLevelBrowse: 3,
    owner: [Object],
    contractLanguage: 0,
    contractState: 1410,
    modifiedAt: '2021-10-11T16:45:48.235Z',
    disabled: false,
    activeOn: '2018-06-18T13:27:21.000Z',
    totalBaseAmount: '2200.000000000',
    name: 'Mayer1',
    owningGroup: [Object]
  }
]
}


/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


exports.accounts = {
  '@type': 'org.openmdx.kernel.ResultSet',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account',
    '@hasMore': 'false',
    '@total': '12',
    objects: [
  {
    '@type': 'org.opencrx.kernel.account1.LegalEntity',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/97NB4O91UQORTH2MA4T2TYJFL',
    '@version': 'bW9kaWZpZWRBdD0yMDE5LTA1LTI2VDEyOjAxOjAxLjI3ODAwMFo=',
    fullName: 'Telekom AG',
    owningUser: [Object],
    vcard: 'BEGIN:VCARD\n' +
        'VERSION:3.0\n' +
        'UID:97NB4O91UQORTH2MA4T2TYJFL\n' +
        'REV:20190526T120101Z\n' +
        'N:Telekom AG\n' +
        'FN:Telekom AG\n' +
        'ADR;WORK:;;Konrad Adenauer Allee 9;Bonn;;53111;Germany\n' +
        'END:VCARD\n',
    externalLink: [Object],
    industry: 26,
    accessLevelUpdate: 2,
    createdBy: [Object],
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/97NB4O91UQORTH2MA4T2TYJFL',
    modifiedAt: '2019-05-26T12:01:01.278Z',
    disabled: false,
    accountRating: 1,
    modifiedBy: [Object],
    accessLevelDelete: 2,
    numberOfEmployeesCategory: 5,
    createdAt: '2019-05-26T12:01:01.278Z',
    accessLevelBrowse: 3,
    owner: [Object],
    accountState: 1,
    name: 'Telekom AG',
    owningGroup: [Object]
  },
  {
    '@type': 'org.opencrx.kernel.account1.LegalEntity',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/9DXSJ5D62FBHLH2MA4T2TYJFL',
    '@version': 'bW9kaWZpZWRBdD0yMDE5LTA1LTI2VDEyOjA0OjI1LjYxNjAwMFo=',
    fullName: 'Germania GmbH',
    owningUser: [Object],
    vcard: 'BEGIN:VCARD\n' +
        'VERSION:3.0\n' +
        'UID:9DXSJ5D62FBHLH2MA4T2TYJFL\n' +
        'REV:20190526T120425Z\n' +
        'N:Germania GmbH\n' +
        'FN:Germania GmbH\n' +
        'ADR;WORK:;;Schlossallee 2;Bonn;;53111;--none--\n' +
        'END:VCARD\n',
    externalLink: [Object],
    industry: 5,
    accessLevelUpdate: 2,
    createdBy: [Object],
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/9DXSJ5D62FBHLH2MA4T2TYJFL',
    modifiedAt: '2019-05-26T12:04:25.616Z',
    disabled: false,
    accountRating: 3,
    modifiedBy: [Object],
    accessLevelDelete: 2,
    numberOfEmployeesCategory: 0,
    createdAt: '2019-05-26T12:04:25.616Z',
    accessLevelBrowse: 3,
    owner: [Object],
    accountState: 1,
    name: 'Germania GmbH',
    owningGroup: [Object]
  },
  {
    '@type': 'org.opencrx.kernel.account1.LegalEntity',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/9DXSJ6MJS0KX5H2MA4T2TYJFL',
    '@version': 'bW9kaWZpZWRBdD0yMDE5LTA1LTI2VDEyOjA1OjM2LjE0NDAwMFo=',
    fullName: 'Dirk Müller GmbH',
    owningUser: [Object],
    vcard: 'BEGIN:VCARD\n' +
        'VERSION:3.0\n' +
        'UID:9DXSJ6MJS0KX5H2MA4T2TYJFL\n' +
        'REV:20190526T120536Z\n' +
        'N:Dirk Müller GmbH\n' +
        'FN:Dirk Müller GmbH\n' +
        'ADR;WORK:;;Weberstraße 1;Bonn;;53115;--none--\n' +
        'END:VCARD\n',
    externalLink: [Object],
    industry: 5,
    accessLevelUpdate: 2,
    createdBy: [Object],
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/9DXSJ6MJS0KX5H2MA4T2TYJFL',
    modifiedAt: '2019-05-26T12:05:36.144Z',
    disabled: false,
    accountRating: 3,
    modifiedBy: [Object],
    accessLevelDelete: 2,
    numberOfEmployeesCategory: 3,
    createdAt: '2019-05-26T12:05:36.144Z',
    accessLevelBrowse: 3,
    owner: [Object],
    accountState: 1,
    name: 'Dirk Müller GmbH',
    owningGroup: [Object]
  },
  {
    '@type': 'org.opencrx.kernel.account1.Contact',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/9ENFSDRCBESBTH2MA4T2TYJFL',
    '@version': 'bW9kaWZpZWRBdD0yMDE5LTA1LTI2VDEzOjI0OjM2Ljk3NDAwMFo=',
    fullName: 'Smith, John Steven',
    owningUser: [Object],
    gender: 1,
    organization: 'SmartHoover Ltd.',
    vcard: 'BEGIN:VCARD\n' +
        'VERSION:3.0\n' +
        'UID:9ENFSDRCBESBTH2MA4T2TYJFL\n' +
        'REV:20190526T132437Z\n' +
        'N:Smith;John;Steven;Mr.;\n' +
        'FN:John Steven Smith\n' +
        'NICKNAME:Steve\n' +
        'ORG:SmartHoover Ltd.\n' +
        'TITLE:Senior Salesman\n' +
        'TEL;WORK;VOICE:01233 33232\n' +
        'ADR;WORK:;;Liverpool Road;London;;;Great Britain\n' +
        'END:VCARD\n',
    doNotPhone: false,
    externalLink: [Object],
    accessLevelUpdate: 2,
    createdBy: [Object],
    doNotBulkPostalMail: false,
    preferredWrittenLanguage: 110,
    doNotFax: false,
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/9ENFSDRCBESBTH2MA4T2TYJFL',
    doNotPostalMail: false,
    modifiedAt: '2019-05-26T13:24:36.974Z',
    disabled: false,
    accountRating: 0,
    doNotEMail: false,
    education: 7,
    department: 'Sales',
    jobRole: 'Senior Salesman',
    annualIncomeCurrency: 978,
    modifiedBy: [Object],
    firstName: 'John',
    jobTitle: 'Senior Salesman',
    accessLevelDelete: 2,
    preferredSpokenLanguage: 110,
    middleName: 'Steven',
    createdAt: '2019-05-26T13:24:36.974Z',
    governmentId: 90123,
    nickName: 'Steve',
    lastName: 'Smith',
    closingCode: 201,
    preferredContactMethod: 3,
    familyStatus: 1,
    owner: [Object],
    accessLevelBrowse: 3,
    accountState: 1,
    owningGroup: [Object],
    salutationCode: 1
  },
  {
    '@type': 'org.opencrx.kernel.account1.Contact',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/9EVAJAOUTHPT5H84KQGL5CLHT',
    '@version': 'bW9kaWZpZWRBdD0yMDE5LTA0LTExVDE2OjE0OjUzLjg3NjAwMFo=',
    fullName: 'Alda, Sascha',
    owningUser: [Object],
    gender: 0,
    vcard: 'BEGIN:VCARD\n' +
        'VERSION:3.0\n' +
        'UID:9EVAJAOUTHPT5H84KQGL5CLHT\n' +
        'REV:20190411T161454Z\n' +
        'N:Alda;Sascha;;Dr.;\n' +
        'FN:Sascha Alda\n' +
        'END:VCARD\n',
    doNotPhone: false,
    externalLink: [Object],
    accessLevelUpdate: 2,
    createdBy: [Object],
    doNotBulkPostalMail: false,
    preferredWrittenLanguage: 0,
    doNotFax: false,
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/9EVAJAOUTHPT5H84KQGL5CLHT',
    doNotPostalMail: false,
    modifiedAt: '2019-04-11T16:14:53.876Z',
    disabled: false,
    accountRating: 0,
    doNotEMail: false,
    education: 0,
    annualIncomeCurrency: 0,
    modifiedBy: [Object],
    firstName: 'Sascha',
    accessLevelDelete: 2,
    preferredSpokenLanguage: 0,
    createdAt: '2019-04-11T16:14:53.876Z',
    lastName: 'Alda',
    closingCode: 0,
    preferredContactMethod: 0,
    familyStatus: 0,
    owner: [Object],
    accessLevelBrowse: 3,
    accountState: 0,
    owningGroup: [Object],
    salutationCode: 8
  },
  {
    '@type': 'org.opencrx.kernel.account1.LegalEntity',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/9K9OSN1V4YY95H2MA4T2TYJFL',
    '@version': 'bW9kaWZpZWRBdD0yMDE5LTA1LTI2VDEyOjAyOjMyLjg1NzAwMFo=',
    fullName: 'Mayer Werft AG',
    owningUser: [Object],
    vcard: 'BEGIN:VCARD\n' +
        'VERSION:3.0\n' +
        'UID:9K9OSN1V4YY95H2MA4T2TYJFL\n' +
        'REV:20190526T120232Z\n' +
        'N:Mayer Werft AG\n' +
        'FN:Mayer Werft AG\n' +
        'ADR;WORK:;;Mayer-Straße 11;Hamburg;;11111;--none--\n' +
        'END:VCARD\n',
    externalLink: [Object],
    industry: 42,
    accessLevelUpdate: 2,
    createdBy: [Object],
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/9K9OSN1V4YY95H2MA4T2TYJFL',
    modifiedAt: '2019-05-26T12:02:32.857Z',
    disabled: false,
    accountRating: 2,
    modifiedBy: [Object],
    accessLevelDelete: 2,
    numberOfEmployeesCategory: 5,
    createdAt: '2019-05-26T12:02:32.857Z',
    accessLevelBrowse: 3,
    owner: [Object],
    accountState: 1,
    name: 'Mayer Werft AG',
    owningGroup: [Object]
  },
  {
    '@type': 'org.opencrx.kernel.account1.Contact',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/L0NTAXG7TQTPM0EBHQA5MAZ7J',
    '@version': 'bW9kaWZpZWRBdD0yMDIxLTAxLTA1VDEwOjEzOjU0LjEzNTAwMFo=',
    fullName: 'Sallinger, Mary-Ann',
    owningUser: [Object],
    gender: 2,
    organization: 'SmartHoover Ltd.',
    vcard: 'BEGIN:VCARD\r\n' +
        'VERSION:3.0\r\n' +
        'UID:L0NTAXG7TQTPM0EBHQA5MAZ7J\r\n' +
        'REV:20200107T093009Z\r\n' +
        'N:Sallinger;Mary-Ann;;Mrs.;\r\n' +
        'FN:Mary-Ann Sallinger\r\n' +
        'NICKNAME:Mary\r\n' +
        'ORG:SmartHoover Ltd.\r\n' +
        'TITLE:Senior Salesman\r\n' +
        'TEL;WORK;VOICE:1233 771233\r\n' +
        'TEL;HOME;VOICE:01753  88213229\r\n' +
        'ADR;WORK:;;Gilliat Rd;Slough;;SL1;Great Britain\r\n' +
        'EMAIL;TYPE=INTERNET,HOME:mary8126363@vk.ru\r\n' +
        'END:VCARD',
    doNotPhone: false,
    externalLink: [Object],
    accessLevelUpdate: 2,
    createdBy: [Object],
    doNotBulkPostalMail: false,
    preferredWrittenLanguage: 110,
    doNotFax: false,
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/L0NTAXG7TQTPM0EBHQA5MAZ7J',
    doNotPostalMail: false,
    modifiedAt: '2021-01-05T10:13:54.135Z',
    disabled: false,
    accountRating: 0,
    doNotEMail: false,
    education: 7,
    department: 'Sales',
    jobRole: 'Senior Salesman',
    annualIncomeCurrency: 978,
    modifiedBy: [Object],
    firstName: 'Mary-Ann',
    jobTitle: 'Senior Salesman',
    accessLevelDelete: 2,
    preferredSpokenLanguage: 110,
    createdAt: '2020-01-07T09:30:09.196Z',
    governmentId: 90124,
    nickName: 'Mary',
    lastName: 'Sallinger',
    closingCode: 1,
    preferredContactMethod: 3,
    familyStatus: 1,
    owner: [Object],
    accessLevelBrowse: 3,
    accountState: 1,
    owningGroup: [Object],
    salutationCode: 2
  },
  {
    '@type': 'org.opencrx.kernel.account1.Contact',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/NI7XwEIBEd29BeMf4vj8cA',
    '@version': 'bW9kaWZpZWRBdD0yMDA5LTA3LTIxVDE3OjExOjE3Ljc0NjAwMFo=',
    fullName: 'Guest,',
    owningUser: [Object],
    gender: 0,
    vcard: 'BEGIN:VCARD\n' +
        'VERSION:2.1\n' +
        'UID:NI7XwEIBEd29BeMf4vj8cA\n' +
        'REV:20090721T151117Z\n' +
        'N:Guest;;;;\n' +
        'FN: Guest\n' +
        'END:VCARD\n',
    doNotPhone: false,
    externalLink: [Object],
    accessLevelUpdate: 2,
    createdBy: [Object],
    doNotBulkPostalMail: false,
    preferredWrittenLanguage: 0,
    doNotFax: false,
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/NI7XwEIBEd29BeMf4vj8cA',
    doNotPostalMail: false,
    modifiedAt: '2009-07-21T17:11:17.746Z',
    disabled: false,
    accountRating: 0,
    doNotEMail: false,
    education: 0,
    annualIncomeCurrency: 0,
    modifiedBy: [Object],
    accessLevelDelete: 2,
    preferredSpokenLanguage: 0,
    createdAt: '2008-06-24T17:21:35.359Z',
    lastName: 'Guest',
    closingCode: 0,
    preferredContactMethod: 0,
    familyStatus: 0,
    owner: [Object],
    accessLevelBrowse: 3,
    accountState: 0,
    owningGroup: [Object],
    salutationCode: 0
  },
  {
    '@type': 'org.opencrx.kernel.account1.Contact',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/RC9375R5ALYW9H84KQGL5CLHT',
    '@version': 'bW9kaWZpZWRBdD0yMDE5LTA1LTEwVDIwOjU1OjI5LjI4MTAwMFo=',
    placeOfOrigin: 'Bonn',
    birthdate: '1994-11-03T00:00:00.000Z',
    fullName: 'Wilken, Kilian',
    owningUser: [Object],
    gender: 1,
    organization: 'ProSyWis',
    vcard: 'BEGIN:VCARD\r\n' +
        'VERSION:3.0\r\n' +
        'UID:RC9375R5ALYW9H84KQGL5CLHT\r\n' +
        'REV:20190510T205453Z\r\n' +
        'N:Wilken;Kilian;;Mr.;\r\n' +
        'FN:Kilian Wilken\r\n' +
        'NICKNAME:Kilian\r\n' +
        'ORG:ProSyWis\r\n' +
        'TITLE:Software-Engineer\r\n' +
        'BDAY:19941103T000000Z\r\n' +
        'TEL;WORK;VOICE:012334456789\r\n' +
        'ADR;WORK:;;Musterstraße 24;Bonn;;53225;Germany\r\n' +
        'END:VCARD',
    doNotPhone: true,
    externalLink: [Object],
    accessLevelUpdate: 2,
    createdBy: [Object],
    doNotBulkPostalMail: true,
    preferredWrittenLanguage: 110,
    doNotFax: true,
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/RC9375R5ALYW9H84KQGL5CLHT',
    doNotPostalMail: false,
    modifiedAt: '2019-05-10T20:55:29.281Z',
    disabled: false,
    accountRating: 0,
    doNotEMail: false,
    education: 7,
    department: 'IT',
    annualIncomeCurrency: 978,
    modifiedBy: [Object],
    firstName: 'Kilian',
    jobTitle: 'Software-Engineer',
    accessLevelDelete: 2,
    aliasName: 'KW',
    preferredSpokenLanguage: 138,
    createdAt: '2019-04-24T11:41:32.336Z',
    nickName: 'Kilian',
    lastName: 'Wilken',
    annualIncomeAmount: '100000.000000000',
    closingCode: 101,
    preferredContactMethod: 1,
    familyStatus: 0,
    owner: [Object],
    accessLevelBrowse: 3,
    placeOfBirth: 'Bonn',
    accountState: 0,
    owningGroup: [Object],
    salutationCode: 1
  },
  {
    '@type': 'org.opencrx.kernel.account1.Contact',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/admin-Standard',
    '@version': 'bW9kaWZpZWRBdD0yMDA5LTA3LTIxVDE3OjExOjQ0Ljc0MTAwMFo=',
    fullName: 'admin-Standard,',
    owningUser: [Object],
    gender: 0,
    vcard: 'BEGIN:VCARD\n' +
        'VERSION:2.1\n' +
        'UID:admin-Standard\n' +
        'REV:20090721T151144Z\n' +
        'N:admin-Standard;;;;\n' +
        'FN: admin-Standard\n' +
        'END:VCARD\n',
    doNotPhone: false,
    externalLink: [Object],
    accessLevelUpdate: 2,
    createdBy: [Object],
    doNotBulkPostalMail: false,
    preferredWrittenLanguage: 0,
    doNotFax: false,
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/admin-Standard',
    doNotPostalMail: false,
    modifiedAt: '2009-07-21T17:11:44.741Z',
    disabled: false,
    accountRating: 0,
    doNotEMail: false,
    education: 0,
    annualIncomeCurrency: 0,
    modifiedBy: [Object],
    accessLevelDelete: 2,
    preferredSpokenLanguage: 0,
    createdAt: '2008-06-24T16:10:16.109Z',
    lastName: 'admin-Standard',
    closingCode: 0,
    preferredContactMethod: 0,
    familyStatus: 0,
    owner: [Object],
    accessLevelBrowse: 3,
    accountState: 0,
    owningGroup: [Object],
    salutationCode: 0
  },
  {
    '@type': 'org.opencrx.kernel.account1.Group',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/admin-Standard~Private',
    '@version': 'bW9kaWZpZWRBdD0yMDEwLTAzLTMxVDE4OjE3OjA2LjU1ODAwMFo=',
    fullName: 'admin-Standard~Private',
    owningUser: [Object],
    vcard: 'BEGIN:VCARD\n' +
        'VERSION:2.1\n' +
        'UID:admin-Standard~Private\n' +
        'REV:20100331T161706Z\n' +
        'N:admin-Standard~Private\n' +
        'FN:admin-Standard~Private\n' +
        'END:VCARD\n',
    externalLink: [Object],
    accessLevelUpdate: 2,
    createdBy: [Object],
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/admin-Standard~Private',
    modifiedAt: '2010-03-31T18:17:06.558Z',
    accountRating: 0,
    modifiedBy: [Object],
    accessLevelDelete: 2,
    createdAt: '2010-03-31T18:17:06.558Z',
    accessLevelBrowse: 3,
    owner: [Object],
    accountState: 0,
    name: 'admin-Standard~Private',
    owningGroup: [Object]
  },
  {
    '@type': 'org.opencrx.kernel.account1.Group',
    '@href': 'https://sepp-crm.inf.h-brs.de/opencrx-rest-CRX/org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/guest~Private',
    '@version': 'bW9kaWZpZWRBdD0yMDEwLTAzLTMxVDE4OjE4OjE3Ljg1MTAwMFo=',
    fullName: 'guest~Private',
    owningUser: [Object],
    vcard: 'BEGIN:VCARD\n' +
        'VERSION:2.1\n' +
        'UID:guest~Private\n' +
        'REV:20100331T161817Z\n' +
        'N:guest~Private\n' +
        'FN:guest~Private\n' +
        'END:VCARD\n',
    externalLink: [Object],
    accessLevelUpdate: 2,
    createdBy: [Object],
    identity: 'xri://@openmdx*org.opencrx.kernel.account1/provider/CRX/segment/Standard/account/guest~Private',
    modifiedAt: '2010-03-31T18:18:17.851Z',
    accountRating: 0,
    modifiedBy: [Object],
    accessLevelDelete: 2,
    createdAt: '2010-03-31T18:18:17.851Z',
    accessLevelBrowse: 3,
    owner: [Object],
    accountState: 0,
    name: 'guest~Private',
    owningGroup: [Object]
  }
]
}

